# https://help.github.com/en/actions/automating-your-workflow-with-github-actions

name: CI
on: [push, pull_request]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2019-11-06
          profile: minimal
          components: rustfmt
          override: true
      - run: cargo fmt -- --check
      - run: |
          for manifest in examples/*/Cargo.toml; do
            cargo fmt --manifest-path "$manifest" -- --check
          done

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.39.0
          profile: minimal
          components: clippy
          override: true
      - run: cargo clippy --all-targets --features strict,futures03
      - run: |
          for manifest in examples/*/Cargo.toml; do
            cargo clippy --manifest-path "$manifest" --all-targets --features strict
          done

  test:
    strategy:
      matrix:
        toolchain: [1.39.0, nightly-2019-11-06]
        features:
          - ''
          - --features futures03
          - --features proc_macro
          - --features futures03,proc_macro
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true
      - run: cargo test --no-default-features ${{ matrix.features }}
